version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  inventory-tracking:
    build: ./
    ports:
      - 3000:3000
    deploy:
      replicas: 1
    # volumes:
    #   - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/inventory_tracking
      - NODE_ENV=production
volumes:
  postgres-data:
